#!/usr/bin/env bash

USER_NAME=$SUDO_USER
HOME_DIR=$(eval echo ~$USER_NAME)

INSTALL_PATH=$HOME_DIR/scrach/.dotfiles

# download from wget
wget -O /tmp/dotConfig.zip https://github.com/abhiroopdatta7/.dotfiles/archive/refs/heads/main.zip
unzip -o /tmp/dotConfig.zip -d /tmp && mv /tmp/.dotfiles-main $INSTALL_PATH

$INSTALL_PATH/setup