#!/bin/bash
set -ex

# if [ $(id -u) -ne 0 ]
#   then printf "Please run this script using sudo!\n"
#   exit
# fi

# HOME_DIR=$(eval echo ~$SUDO_USER)
HOME_DIR=$(eval echo ~$USER)

INSTALL_PATH=${HOME_DIR}/.dotfiles
# INSTALL_PATH=$(pwd)

# download from wget
wget -O /tmp/dotConfig.zip https://github.com/abhiroopdatta7/.dotfiles/archive/refs/heads/main.zip
unzip -o /tmp/dotConfig.zip -d /tmp && mv /tmp/.dotfiles-main ${INSTALL_PATH}

source ${INSTALL_PATH}/setup
