#!/usr/bin/env bash
# Configuration Manager -A7d

USER_NAME = ${SUDO_USER}
HOME_DIR=$(eval echo ~${USER_NAME})

if [ $(id -u) -ne 0 ]
  then echo "Please run this script using sudo!"
  exit
fi

source ./scripts/checkbox.sh --message="A7d" --options="zsh|tmux|nvim" --multiple
clear

if [[ ${#checkbox_output[@]} -gt 0 ]]; then

    echo "Preparing..."
    apt-get -qq update && apt-get -qq install -y stow

    for option in "${checkbox_output[@]}"; do
        
        echo "Installing & Configuring ${option}"
        stow ${option} --ignore='' --target=${HOME_DIR}
        ./${option}/install.debian
    done
else
        printf "Thank you ${USER_NAME}\n"
    fi