#!/bin/bash
set -e

# Configuration Manager -A7d

# if [ $(id -u) -ne 0 ]
#   then printf "Please run this script using sudo!\n"
#   exit
# fi

HOME_DIR=$(eval echo ~$USER)
os_type=$(awk -F'=' '/^ID_LIKE=/ {print $2}' /etc/os-release | tr -d '"')

source ./scripts/checkbox.sh --message="h: Help" --options="zsh|tmux|nvim" --multiple
clear

if [[ ${#checkbox_output[@]} -gt 0 ]]; then

    printf "Preparing...\n"
    source ./scripts/prepare.$os_type

    for option in "${checkbox_output[@]}"; do
        
        printf "Installing & Configuring $option\n"
        stow --ignore='install.*' --target=$HOME_DIR $option
        source ./$option/install.$os_type
    done

    printf "Congratulations $USER! configurations are stored at $HOME_DIR/.dotfiles\n"
else
    printf "Thank you $USER\n"
fi
